/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'assignmentCount' : bigint,
  'passMarks' : bigint,
  'difficulty' : string,
  'description' : string,
  'gradeLevel' : bigint,
  'objectives' : string,
  'syllabus' : string,
}
export interface EnrollmentRecord {
  'studentName' : string,
  'gradeLevel' : bigint,
  'student' : Principal,
  'enrollmentDate' : Time,
  'courseId' : bigint,
}
export interface FeeStructure { 'annualFee' : bigint, 'monthlyFee' : bigint }
export interface PaymentRecord {
  'id' : bigint,
  'status' : PaymentStatus,
  'paymentDate' : Time,
  'student' : Principal,
  'paymentType' : PaymentType,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type PaymentType = { 'annual' : null } |
  { 'monthly' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkPaymentStatus' : ActorMethod<[Principal, bigint], [] | [PaymentStatus]>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourseById' : ActorMethod<[bigint], [] | [Course]>,
  'getCoursesByDifficulty' : ActorMethod<[string], Array<Course>>,
  'getCoursesByGrade' : ActorMethod<[bigint], Array<Course>>,
  'getCoursesByGradeAndDifficulty' : ActorMethod<
    [bigint, string],
    Array<Course>
  >,
  'getCoursesBySubject' : ActorMethod<[string], Array<Course>>,
  'getCoursesBySubjectAndDifficulty' : ActorMethod<
    [string, string],
    Array<Course>
  >,
  'getCoursesBySubjectAndGrade' : ActorMethod<[string, bigint], Array<Course>>,
  'getCoursesBySubjectGradeAndDifficulty' : ActorMethod<
    [string, bigint, string],
    Array<Course>
  >,
  'getEnrollmentStatus' : ActorMethod<[Principal], Array<EnrollmentRecord>>,
  'getFeeStructure' : ActorMethod<[], FeeStructure>,
  'getPaymentHistory' : ActorMethod<[Principal], Array<PaymentRecord>>,
  'getSubjectList' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initiatePayment' : ActorMethod<[PaymentType], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCourseEnrollments' : ActorMethod<[bigint], Array<EnrollmentRecord>>,
  'recordPaymentCompletion' : ActorMethod<
    [Principal, bigint, boolean],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitEnrollment' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];