/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'assignmentCount' : IDL.Nat,
  'passMarks' : IDL.Nat,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'gradeLevel' : IDL.Nat,
  'objectives' : IDL.Text,
  'syllabus' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const EnrollmentRecord = IDL.Record({
  'studentName' : IDL.Text,
  'gradeLevel' : IDL.Nat,
  'student' : IDL.Principal,
  'enrollmentDate' : Time,
  'courseId' : IDL.Nat,
});
export const FeeStructure = IDL.Record({
  'annualFee' : IDL.Nat,
  'monthlyFee' : IDL.Nat,
});
export const PaymentType = IDL.Variant({
  'annual' : IDL.Null,
  'monthly' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'paymentDate' : Time,
  'student' : IDL.Principal,
  'paymentType' : PaymentType,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkPaymentStatus' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Opt(PaymentStatus)],
      ['query'],
    ),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCoursesByDifficulty' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'getCoursesByGrade' : IDL.Func([IDL.Nat], [IDL.Vec(Course)], ['query']),
  'getCoursesByGradeAndDifficulty' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Course)],
      ['query'],
    ),
  'getCoursesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'getCoursesBySubjectAndDifficulty' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Course)],
      ['query'],
    ),
  'getCoursesBySubjectAndGrade' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Course)],
      ['query'],
    ),
  'getCoursesBySubjectGradeAndDifficulty' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Vec(Course)],
      ['query'],
    ),
  'getEnrollmentStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EnrollmentRecord)],
      ['query'],
    ),
  'getFeeStructure' : IDL.Func([], [FeeStructure], ['query']),
  'getPaymentHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getSubjectList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initiatePayment' : IDL.Func([PaymentType], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCourseEnrollments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EnrollmentRecord)],
      ['query'],
    ),
  'recordPaymentCompletion' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEnrollment' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'assignmentCount' : IDL.Nat,
    'passMarks' : IDL.Nat,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'gradeLevel' : IDL.Nat,
    'objectives' : IDL.Text,
    'syllabus' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const EnrollmentRecord = IDL.Record({
    'studentName' : IDL.Text,
    'gradeLevel' : IDL.Nat,
    'student' : IDL.Principal,
    'enrollmentDate' : Time,
    'courseId' : IDL.Nat,
  });
  const FeeStructure = IDL.Record({
    'annualFee' : IDL.Nat,
    'monthlyFee' : IDL.Nat,
  });
  const PaymentType = IDL.Variant({
    'annual' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'paymentDate' : Time,
    'student' : IDL.Principal,
    'paymentType' : PaymentType,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkPaymentStatus' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Opt(PaymentStatus)],
        ['query'],
      ),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCoursesByDifficulty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getCoursesByGrade' : IDL.Func([IDL.Nat], [IDL.Vec(Course)], ['query']),
    'getCoursesByGradeAndDifficulty' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getCoursesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
    'getCoursesBySubjectAndDifficulty' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getCoursesBySubjectAndGrade' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getCoursesBySubjectGradeAndDifficulty' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getEnrollmentStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EnrollmentRecord)],
        ['query'],
      ),
    'getFeeStructure' : IDL.Func([], [FeeStructure], ['query']),
    'getPaymentHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getSubjectList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initiatePayment' : IDL.Func([PaymentType], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCourseEnrollments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EnrollmentRecord)],
        ['query'],
      ),
    'recordPaymentCompletion' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEnrollment' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };