/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Course {
    id: bigint;
    title: string;
    subject: string;
    assignmentCount: bigint;
    passMarks: bigint;
    difficulty: string;
    description: string;
    gradeLevel: bigint;
    objectives: string;
    syllabus: string;
}
export type Time = bigint;
export interface PaymentRecord {
    id: bigint;
    status: PaymentStatus;
    paymentDate: Time;
    student: Principal;
    paymentType: PaymentType;
    amount: bigint;
}
export interface EnrollmentRecord {
    studentName: string;
    gradeLevel: bigint;
    student: Principal;
    enrollmentDate: Time;
    courseId: bigint;
}
export interface UserProfile {
    name: string;
}
export interface FeeStructure {
    annualFee: bigint;
    monthlyFee: bigint;
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum PaymentType {
    annual = "annual",
    monthly = "monthly"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkPaymentStatus(student: Principal, paymentId: bigint): Promise<PaymentStatus | null>;
    getAllCourses(): Promise<Array<Course>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCourseById(courseId: bigint): Promise<Course | null>;
    getCoursesByDifficulty(difficulty: string): Promise<Array<Course>>;
    getCoursesByGrade(grade: bigint): Promise<Array<Course>>;
    getCoursesByGradeAndDifficulty(grade: bigint, difficulty: string): Promise<Array<Course>>;
    getCoursesBySubject(subject: string): Promise<Array<Course>>;
    getCoursesBySubjectAndDifficulty(subject: string, difficulty: string): Promise<Array<Course>>;
    getCoursesBySubjectAndGrade(subject: string, grade: bigint): Promise<Array<Course>>;
    getCoursesBySubjectGradeAndDifficulty(subject: string, grade: bigint, difficulty: string): Promise<Array<Course>>;
    getEnrollmentStatus(student: Principal): Promise<Array<EnrollmentRecord>>;
    getFeeStructure(): Promise<FeeStructure>;
    getPaymentHistory(student: Principal): Promise<Array<PaymentRecord>>;
    getSubjectList(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initiatePayment(paymentType: PaymentType): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    listCourseEnrollments(courseId: bigint): Promise<Array<EnrollmentRecord>>;
    recordPaymentCompletion(student: Principal, paymentId: bigint, success: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitEnrollment(courseId: bigint, gradeLevel: bigint): Promise<void>;
}
import type { Course as _Course, PaymentRecord as _PaymentRecord, PaymentStatus as _PaymentStatus, PaymentType as _PaymentType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkPaymentStatus(arg0: Principal, arg1: bigint): Promise<PaymentStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkPaymentStatus(arg0, arg1);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkPaymentStatus(arg0, arg1);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseById(arg0: bigint): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseById(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseById(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoursesByDifficulty(arg0: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByDifficulty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByDifficulty(arg0);
            return result;
        }
    }
    async getCoursesByGrade(arg0: bigint): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByGrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByGrade(arg0);
            return result;
        }
    }
    async getCoursesByGradeAndDifficulty(arg0: bigint, arg1: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByGradeAndDifficulty(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByGradeAndDifficulty(arg0, arg1);
            return result;
        }
    }
    async getCoursesBySubject(arg0: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesBySubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesBySubject(arg0);
            return result;
        }
    }
    async getCoursesBySubjectAndDifficulty(arg0: string, arg1: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesBySubjectAndDifficulty(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesBySubjectAndDifficulty(arg0, arg1);
            return result;
        }
    }
    async getCoursesBySubjectAndGrade(arg0: string, arg1: bigint): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesBySubjectAndGrade(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesBySubjectAndGrade(arg0, arg1);
            return result;
        }
    }
    async getCoursesBySubjectGradeAndDifficulty(arg0: string, arg1: bigint, arg2: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesBySubjectGradeAndDifficulty(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesBySubjectGradeAndDifficulty(arg0, arg1, arg2);
            return result;
        }
    }
    async getEnrollmentStatus(arg0: Principal): Promise<Array<EnrollmentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnrollmentStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnrollmentStatus(arg0);
            return result;
        }
    }
    async getFeeStructure(): Promise<FeeStructure> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStructure();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStructure();
            return result;
        }
    }
    async getPaymentHistory(arg0: Principal): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentHistory(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentHistory(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectList(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectList();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async initiatePayment(arg0: PaymentType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.initiatePayment(to_candid_PaymentType_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiatePayment(to_candid_PaymentType_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCourseEnrollments(arg0: bigint): Promise<Array<EnrollmentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourseEnrollments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourseEnrollments(arg0);
            return result;
        }
    }
    async recordPaymentCompletion(arg0: Principal, arg1: bigint, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPaymentCompletion(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPaymentCompletion(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitEnrollment(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnrollment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnrollment(arg0, arg1);
            return result;
        }
    }
}
function from_candid_PaymentRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentType): PaymentType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentStatus]): PaymentStatus | null {
    return value.length === 0 ? null : from_candid_PaymentStatus_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    paymentDate: _Time;
    student: Principal;
    paymentType: _PaymentType;
    amount: bigint;
}): {
    id: bigint;
    status: PaymentStatus;
    paymentDate: Time;
    student: Principal;
    paymentType: PaymentType;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n4(_uploadFile, _downloadFile, value.status),
        paymentDate: value.paymentDate,
        student: value.student,
        paymentType: from_candid_PaymentType_n13(_uploadFile, _downloadFile, value.paymentType),
        amount: value.amount
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annual: null;
} | {
    monthly: null;
}): PaymentType {
    return "annual" in value ? PaymentType.annual : "monthly" in value ? PaymentType.monthly : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecord>): Array<PaymentRecord> {
    return value.map((x)=>from_candid_PaymentRecord_n11(_uploadFile, _downloadFile, x));
}
function to_candid_PaymentType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): _PaymentType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): {
    annual: null;
} | {
    monthly: null;
} {
    return value == PaymentType.annual ? {
        annual: null
    } : value == PaymentType.monthly ? {
        monthly: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
